### ISSUE TITLE
Import error for cuequivariance_ops_torch even in a brand new conda env

### ISSUE THREAD

**Issue by ShaunHan** [NVIDIA/cuEquivariance#193]
Hi, I am facing some issues installing cuequivariance-ops-torch-cu12. I made a clean new Python 3.11 conda env and then `pip install torch cuequivariance cuequivariance-torch cuequivariance-ops-torch-cu12`. When I try to `import cuequivariance_ops_torch`, I get the following error:
```
Error while loading libcue_ops.so: libcublas.so.12: cannot open shared object file: No such file or directory
/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_ops_torch/__init__.py", line 16, in <module>
    from cuequivariance_ops_torch.segmented_transpose import (
  File "/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_ops_torch/segmented_transpose.py", line 13, in <module>
    import cuequivariance_ops_torch._ext as ops
  File "/fs/cephfs/data/qm_inorganics/venvs/mace_cuequivariance/lib/python3.11/site-packages/cuequivariance_ops_torch/_ext/__init__.py", line 12, in <module>
    from .cuequivariance_ops_torch_ext import *  # light-weight wrapper
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcue_ops.so: cannot open shared object file: No such file or directory
```
This is the same error when we first tried to install cuequivariance_ops_torch in our existing conda env. Does any one know what could be the reason for this error? I am using the NVIDIA H100 NVL GPU, and the glibc version is 2.34. Below is my `pip list`:
```
Package                       Version
----------------------------- ---------
cuequivariance                0.6.1
cuequivariance-ops-cu12       0.6.1
cuequivariance-ops-torch-cu12 0.6.1
cuequivariance-torch          0.6.1
filelock                      3.20.0
fsspec                        2025.9.0
Jinja2                        3.1.6
MarkupSafe                    3.0.3
mpmath                        1.3.0
networkx                      3.5
numpy                         2.3.3
nvidia-cublas-cu12            12.8.4.1
nvidia-cuda-cupti-cu12        12.8.90
nvidia-cuda-nvrtc-cu12        12.8.93
nvidia-cuda-runtime-cu12      12.8.90
nvidia-cudnn-cu12             9.10.2.21
nvidia-cufft-cu12             11.3.3.83
nvidia-cufile-cu12            1.13.1.3
nvidia-curand-cu12            10.3.9.90
nvidia-cusolver-cu12          11.7.3.90
nvidia-cusparse-cu12          12.5.8.93
nvidia-cusparselt-cu12        0.7.1
nvidia-ml-py                  13.580.82
nvidia-nccl-cu12              2.27.3
nvidia-nvjitlink-cu12         12.8.93
nvidia-nvtx-cu12              12.8.90
opt_einsum                    3.4.0
pip                           25.2
platformdirs                  4.5.0
pynvml                        13.0.1
scipy                         1.16.2
setuptools                    80.9.0
sympy                         1.14.0
torch                         2.8.0
tqdm                          4.67.1
triton                        3.4.0
typing_extensions             4.15.0
wheel                         0.45.1
```

**Comment by chaitjo** [comment]
This fixed it for me (I installed cuEq via pip and it seems the library was not being linked to my path properly)
```
export LD_LIBRARY_PATH=/path_to_conda_env/lib/python3.11/site-packages/cuequivariance_ops/lib:$LD_LIBRARY_PATH
```
